### ISSUE TITLE
Gjeldende fase

### ISSUE THREAD

**Issue by oyei** [ks-no/fiks-saksfaser-specification#1]
Innsynsløsninger trenger å vite hvilken fase vi står i i dag. Og de trenger å vite om den fasen åpner for innspill. I GeoIntegrasjon kan en benytte datoer på start/slutt-milepæler til dette, kombinert med en sjekk på fasetype og fasestatus. Det er noe uklart om foreslåtte modell støtter tilsvarende.

![image](https://github.com/user-attachments/assets/1576b8c6-cf4b-43d8-9518-ed621aba8ff1)

**Comment by sturtzel** [comment]
DiBK har egentlig 0..n milepæler pr. fase. Vi får se på om det må være en milepæl i hver ende evt. om man bare må sjekke utført og planlagt dato for milepælene og ut i fra det anta tidsrommet. FaseStatus er nok bedre for å gi info om man er inne i fasen. Da er man uavhengig av milepælene.

**Comment by jarleborsheim** [comment]
Vi lager et brukstilfelle som dokumenterer hvordan man finner ut av dette med den modellen vi har.
Tilsvarende som for andre protokoller.

**Comment by jarleborsheim** [comment]
Vi har begynt på en Wiki og lagt til dette som et brukstilfelle her: https://github.com/ks-no/fiks-saksfaser-specification/wiki#dokumentasjon
